
import os
import pathlib
import subprocess
import generate_rna as gr

# =========================
# 9. 
# =========================

def write_rnacomposer_input(sequence, dot_bracket, out_path):
    with open(out_path, "w") as f:
        f.write(sequence + "\n")
        f.write(dot_bracket + "\n")


def write_farfar2_inputs(sequence, dot_bracket, out_dir, name):
    os.makedirs(out_dir, exist_ok=True)
    fasta_path = os.path.join(out_dir, f"{name}.fasta")
    ss_path = os.path.join(out_dir, f"{name}.secstruct")

    with open(fasta_path, "w") as f:
        f.write(f">{name}\n")
        f.write(sequence + "\n")

    with open(ss_path, "w") as f:
        f.write(dot_bracket + "\n")

    return fasta_path, ss_path


# =========================
# 10. 
# =========================

def run_farfar2(fasta_path, ss_path, out_dir="farfar_outputs", nstruct=5, rosetta_bin="farfar2.macosclangrelease"):
    """
    Call FARFAR2 via command line to generate 3D models (.pdb).
    You MUST have Rosetta/FARFAR2 installed, and adjust 'rosetta_bin' accordingly.
    """
    out_dir = pathlib.Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    cmd = [
        rosetta_bin,
        "-fasta", str(fasta_path),
        "-secstruct_file", str(ss_path),
        "-nstruct", str(nstruct),
        "-out:path:all", str(out_dir),
    ]
    print("Running FARFAR2:", " ".join(cmd))
    subprocess.run(cmd, check=True)

    # FARFAR2 will produce one or more .pdb files in out_dir
    pdb_files = sorted(out_dir.glob("*.pdb"))
    return pdb_files

# =========================
# 11. Convert .pdf to .cif
# =========================

def convert_pdb_to_cif(pdb_path, cif_path, pdb2cif_bin="pdb2cif"):
    """
    Convert a PDB file to CIF using an external command-line tool.
    You must have 'pdb2cif' (or equivalent) installed.
    """
    cmd = [pdb2cif_bin, str(pdb_path)]
    print("Converting to CIF:", " ".join(cmd))
    with open(cif_path, "w") as out_f:
        subprocess.run(cmd, check=True, stdout=out_f)
    return cif_path

# =========================
# 8. Example usage
# =========================

if __name__ == "__main__":
    scaffold_name = "z_tile_tetramer"
    cands = gr.generate_candidates_for_scaffold(scaffold_name, n_candidates=5)

    gr.save_candidates(scaffold_name, cands)

    # Take the best candidate
    best = cands[0]
    seq = best["sequence"]
    ss = best["predicted_ss"]  # or best["target_ss"]

    # 1) Write inputs for FARFAR2
    fasta_path, ss_path = write_farfar2_inputs(
        seq,
        ss,
        out_dir="farfar_inputs",
        name=f"{scaffold_name}_best",
    )

    # 2) Run FARFAR2 to get .pdb models (requires Rosetta installed)
    pdb_files = run_farfar2(fasta_path, ss_path, out_dir="farfar_outputs", nstruct=3)

    # 3) Convert the first PDB to CIF (requires pdb2cif or equivalent)
    if pdb_files:
        first_pdb = pdb_files[0]
        cif_path = first_pdb.with_suffix(".cif")  # same name, .cif extension
        convert_pdb_to_cif(first_pdb, cif_path)
        print("Wrote CIF:", cif_path)
    else:
        print("No PDB files generated by FARFAR2.")
